### ISSUE TITLE
Corrigir script sql

### ISSUE THREAD

**Issue by maikenegreiros** [ciebit/files#16]
No script sql atual está faltando a criação do campo `caption`.

**Comment by maikenegreiros** [comment]
@johnnysaymon , vendo melhor esse repo, percebi que a classe File também não possui um propriedade `caption`. Ela possui uma propriedade `description`, são coisas diferentes?

**Comment by johnnysaymon** [comment]
Não @maikenegreiros . Acredito que deve ser resquícios do projeto anterior. Precisamos agora identificar onde está sendo solicitado o compo `caption`

**Comment by maikenegreiros** [comment]
Onde está sendo solicitado na view? @johnnysaymon

**Comment by johnnysaymon** [comment]
Acredito que a issue foi criada pois ocorria um erro pela falta deste campo, correto? Agora é necessário descobrir que classe está solicitando esse campo para poder fazer a correção alterando para `description`

**Comment by maikenegreiros** [comment]
O erro ocorria no módulo news @johnnysaymon , pois o módulo news usava esse campo. Já esse módulo onde estamos discutindo a issue não apresenta erro algum nos testes

**Comment by johnnysaymon** [comment]
Ah. Compreendi. Então podemos fechar essa issue. Precisamos agora corrigir o módulo News.
